version: "1.0"
services:
    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports: 
            - 1433:1433
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=P@55w0rd
        networks:
            - net 
    frontend:
        build: ./ClientApp
        ports:
            - "3000:3000"
        networks:
            - net
        environment:
            - REACT_APP_ASP_LINK=http://localhost:5000
    webapi:
        build: 
            dockerfile: ./ToDo.WebApi/Dockerfile
            context: .
        environment:
            - ConnectionStrings__ToDoConnection=Data Source=sqlserver;Database=tododatabase;User=SA;Password=P@55w0rd;TrustServerCertificate=true
            - ConnectionStrings__IdentityConnection=Data Source=sqlserver;Database=todoidentitydatabase;User ID=SA;Password=P@55w0rd;TrustServerCertificate=true
            - Frontend=http://localhost:3000
            - SQLServer_path=http://sqlserver:1433
        ports:
            - '5000:80' 
        networks:
            - net
        depends_on:
            - sqlserver

networks:
    net:
        driver: bridge
   
